# Generated by Django 4.2.16 on 2024-10-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="surname",
        ),
    ]
