# Generated by Django 4.2.16 on 2024-10-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_customuser_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="avatar",
        ),
    ]
